"""create black list

Revision ID: 57c267459a8b
Revises: c39ea72b0f6d
Create Date: 2024-07-23 12:27:16.665480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57c267459a8b'
down_revision: Union[str, None] = 'c39ea72b0f6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('JWT_black_list',
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('token'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('JWT_black_list')
    # ### end Alembic commands ###
