"""delete black list

Revision ID: 73bfb19a0a6b
Revises: 57c267459a8b
Create Date: 2024-07-23 14:18:51.690769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73bfb19a0a6b'
down_revision: Union[str, None] = '57c267459a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('JWT_black_list')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('JWT_black_list',
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('token', name='JWT_black_list_pkey')
    )
    # ### end Alembic commands ###
