"""add token field to logger

Revision ID: a89bde9eb355
Revises: 1d76a5460156
Create Date: 2024-07-23 16:01:00.467775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a89bde9eb355'
down_revision: Union[str, None] = '1d76a5460156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_logger', sa.Column('token', sa.String(length=255), nullable=True))
    op.drop_column('auth_logger', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_logger', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('auth_logger', 'token')
    # ### end Alembic commands ###
