"""create logger

Revision ID: c39ea72b0f6d
Revises: 1aada74c1cce
Create Date: 2024-07-23 12:02:40.096753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c39ea72b0f6d'
down_revision: Union[str, None] = '1aada74c1cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_logger', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('auth_logger', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_logger', sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('auth_logger', 'created_at')
    # ### end Alembic commands ###
